version: "3.8"

services:
  api-kawan:
    build: .
    container_name: api-prediksi-container
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - prediksi-network

networks:
  prediksi-network:
    driver: bridge
